### PR TITLE
Fix broken xml in Directory.xml

### PR DESCRIPTION
**Pull request by lanfeust69**

### CODE REVIEW

**Comment by lanfeust69** [comment]
@flofreud : May I know what was wrong with the PR (as compared with #218 for instance) ?

**Comment by flofreud** [comment]
I'm really sorry. :(

I definitively wanted to merge and not close. I was really happy to see the PR, checked it and everything was alright. So I merged it.

At least I thought I did. I really messed this up. Sorry!

**Comment by lanfeust69** [comment]
No problem, actually it was my #1 hypothesis :)

And no real need to re-open, #218 did the job (except maybe for the `type = "text"` attribute, I guess it doesn't matter that much).

**Comment by flofreud** [comment]
So, now there is also the `text = "text"` attribute and everything should be merged correctly. Thanks again for the help and I'm sorry for the inconveniences.

**Pull request merged**
